<?php
?>
<?php

class ARW_Megamenu_Model_System_Config_Source_Category_Attribute_Source_Categoryicon extends Mage_Eav_Model_Entity_Attribute_Source_Abstract
{
	protected $_options;
	
	/**
     * Get list of existing category labels
     */
	public function getAllOptions()
	{
		if (!$this->_options)
		{
            return array(
				array('value'=>'',                      'label'=>''),
                array('value'=>'fa-adjust','label'=>Mage::helper('adminhtml')->__('Adjust')),
                array('value'=>'fa-anchor','label'=>Mage::helper('adminhtml')->__('Anchor')),
                array('value'=>'fa-archive','label'=>Mage::helper('adminhtml')->__('Archive')),
                array('value'=>'fa-arrows','label'=>Mage::helper('adminhtml')->__('Arrows')),
                array('value'=>'fa-arrows-h','label'=>Mage::helper('adminhtml')->__('Arrows h')),
                array('value'=>'fa-arrows-v','label'=>Mage::helper('adminhtml')->__('Arrows v')),
                array('value'=>'fa-asterisk','label'=>Mage::helper('adminhtml')->__('Asterisk')),
                array('value'=>'fa-ban','label'=>Mage::helper('adminhtml')->__('Ban')),
                array('value'=>'fa-bar-chart-o','label'=>Mage::helper('adminhtml')->__('Bar chart o')),
                array('value'=>'fa-barcode','label'=>Mage::helper('adminhtml')->__('Barcode')),
                array('value'=>'fa-bars','label'=>Mage::helper('adminhtml')->__('Bars')),
                array('value'=>'fa-beer','label'=>Mage::helper('adminhtml')->__('Beer')),
                array('value'=>'fa-bell','label'=>Mage::helper('adminhtml')->__('Bell')),
                array('value'=>'fa-bell-o','label'=>Mage::helper('adminhtml')->__('Bell o')),
                array('value'=>'fa-bolt','label'=>Mage::helper('adminhtml')->__('Bolt')),
                array('value'=>'fa-bomb','label'=>Mage::helper('adminhtml')->__('Bomb')),
                array('value'=>'fa-book','label'=>Mage::helper('adminhtml')->__('Book')),
                array('value'=>'fa-bookmark','label'=>Mage::helper('adminhtml')->__('Bookmark')),
                array('value'=>'fa-bookmark-o','label'=>Mage::helper('adminhtml')->__('Bookmark o')),
                array('value'=>'fa-briefcase','label'=>Mage::helper('adminhtml')->__('Briefcase')),
                array('value'=>'fa-bug','label'=>Mage::helper('adminhtml')->__('Bug')),
                array('value'=>'fa-building','label'=>Mage::helper('adminhtml')->__('Building')),
                array('value'=>'fa-building-o','label'=>Mage::helper('adminhtml')->__('Building o')),
                array('value'=>'fa-bullhorn','label'=>Mage::helper('adminhtml')->__('Bullhorn')),
                array('value'=>'fa-bullseye','label'=>Mage::helper('adminhtml')->__('Bullseye')),
                array('value'=>'fa-calendar','label'=>Mage::helper('adminhtml')->__('Calendar')),
                array('value'=>'fa-calendar-o','label'=>Mage::helper('adminhtml')->__('Calendar o')),
                array('value'=>'fa-camera','label'=>Mage::helper('adminhtml')->__('Camera')),
                array('value'=>'fa-camera-retro','label'=>Mage::helper('adminhtml')->__('Camera retro')),
                array('value'=>'fa-car','label'=>Mage::helper('adminhtml')->__('Car')),
                array('value'=>'fa-caret-square-o-down','label'=>Mage::helper('adminhtml')->__('Caret square o down')),
                array('value'=>'fa-caret-square-o-left','label'=>Mage::helper('adminhtml')->__('Caret square o left')),
                array('value'=>'fa-caret-square-o-right','label'=>Mage::helper('adminhtml')->__('Caret square o right')),
                array('value'=>'fa-caret-square-o-up','label'=>Mage::helper('adminhtml')->__('Caret square o up')),
                array('value'=>'fa-certificate','label'=>Mage::helper('adminhtml')->__('Certificate')),
                array('value'=>'fa-check','label'=>Mage::helper('adminhtml')->__('Check')),
                array('value'=>'fa-check-circle','label'=>Mage::helper('adminhtml')->__('Check circle')),
                array('value'=>'fa-check-circle-o','label'=>Mage::helper('adminhtml')->__('Check circle o')),
                array('value'=>'fa-check-square','label'=>Mage::helper('adminhtml')->__('Check square')),
                array('value'=>'fa-check-square-o','label'=>Mage::helper('adminhtml')->__('Check square o')),
                array('value'=>'fa-child','label'=>Mage::helper('adminhtml')->__('Child')),
                array('value'=>'fa-circle','label'=>Mage::helper('adminhtml')->__('Circle')),
                array('value'=>'fa-circle-o','label'=>Mage::helper('adminhtml')->__('Circle o')),
                array('value'=>'fa-circle-o-notch','label'=>Mage::helper('adminhtml')->__('Circle o notch')),
                array('value'=>'fa-circle-thin','label'=>Mage::helper('adminhtml')->__('Circle thin')),
                array('value'=>'fa-clock-o','label'=>Mage::helper('adminhtml')->__('Clock o')),
                array('value'=>'fa-cloud','label'=>Mage::helper('adminhtml')->__('Cloud')),
                array('value'=>'fa-cloud-download','label'=>Mage::helper('adminhtml')->__('Cloud download')),
                array('value'=>'fa-cloud-upload','label'=>Mage::helper('adminhtml')->__('Cloud upload')),
                array('value'=>'fa-code','label'=>Mage::helper('adminhtml')->__('Code')),
                array('value'=>'fa-code-fork','label'=>Mage::helper('adminhtml')->__('Code fork')),
                array('value'=>'fa-coffee','label'=>Mage::helper('adminhtml')->__('Coffee')),
                array('value'=>'fa-cog','label'=>Mage::helper('adminhtml')->__('Cog')),
                array('value'=>'fa-cogs','label'=>Mage::helper('adminhtml')->__('Cogs')),
                array('value'=>'fa-comment','label'=>Mage::helper('adminhtml')->__('Comment')),
                array('value'=>'fa-comment-o','label'=>Mage::helper('adminhtml')->__('Comment o')),
                array('value'=>'fa-comments','label'=>Mage::helper('adminhtml')->__('Comments')),
                array('value'=>'fa-comments-o','label'=>Mage::helper('adminhtml')->__('Comments o')),
                array('value'=>'fa-compass','label'=>Mage::helper('adminhtml')->__('Compass')),
                array('value'=>'fa-credit-card','label'=>Mage::helper('adminhtml')->__('Credit card')),
                array('value'=>'fa-crop','label'=>Mage::helper('adminhtml')->__('Crop')),
                array('value'=>'fa-crosshairs','label'=>Mage::helper('adminhtml')->__('Crosshairs')),
                array('value'=>'fa-cube','label'=>Mage::helper('adminhtml')->__('Cube')),
                array('value'=>'fa-cubes','label'=>Mage::helper('adminhtml')->__('Cubes')),
                array('value'=>'fa-cutlery','label'=>Mage::helper('adminhtml')->__('Cutlery')),
                array('value'=>'fa-database','label'=>Mage::helper('adminhtml')->__('Database')),
                array('value'=>'fa-desktop','label'=>Mage::helper('adminhtml')->__('Desktop')),
                array('value'=>'fa-dot-circle-o','label'=>Mage::helper('adminhtml')->__('Dot circle o')),
                array('value'=>'fa-download','label'=>Mage::helper('adminhtml')->__('Download')),
                array('value'=>'fa-ellipsis-h','label'=>Mage::helper('adminhtml')->__('Ellipsis h')),
                array('value'=>'fa-ellipsis-v','label'=>Mage::helper('adminhtml')->__('Ellipsis v')),
                array('value'=>'fa-envelope','label'=>Mage::helper('adminhtml')->__('Envelope')),
                array('value'=>'fa-envelope-o','label'=>Mage::helper('adminhtml')->__('Envelope o')),
                array('value'=>'fa-envelope-square','label'=>Mage::helper('adminhtml')->__('Envelope square')),
                array('value'=>'fa-eraser','label'=>Mage::helper('adminhtml')->__('Eraser')),
                array('value'=>'fa-exchange','label'=>Mage::helper('adminhtml')->__('Exchange')),
                array('value'=>'fa-exclamation','label'=>Mage::helper('adminhtml')->__('Exclamation')),
                array('value'=>'fa-exclamation-circle','label'=>Mage::helper('adminhtml')->__('Exclamation circle')),
                array('value'=>'fa-exclamation-triangle','label'=>Mage::helper('adminhtml')->__('Exclamation triangle')),
                array('value'=>'fa-external-link','label'=>Mage::helper('adminhtml')->__('External link')),
                array('value'=>'fa-external-link-square','label'=>Mage::helper('adminhtml')->__('External link square')),
                array('value'=>'fa-eye','label'=>Mage::helper('adminhtml')->__('Eye')),
                array('value'=>'fa-eye-slash','label'=>Mage::helper('adminhtml')->__('Eye slash')),
                array('value'=>'fa-fax','label'=>Mage::helper('adminhtml')->__('Fax')),
                array('value'=>'fa-female','label'=>Mage::helper('adminhtml')->__('Female')),
                array('value'=>'fa-fighter-jet','label'=>Mage::helper('adminhtml')->__('Fighter jet')),
                array('value'=>'fa-file-archive-o','label'=>Mage::helper('adminhtml')->__('File archive o')),
                array('value'=>'fa-file-audio-o','label'=>Mage::helper('adminhtml')->__('File audio o')),
                array('value'=>'fa-file-code-o','label'=>Mage::helper('adminhtml')->__('File code o')),
                array('value'=>'fa-file-excel-o','label'=>Mage::helper('adminhtml')->__('File excel o')),
                array('value'=>'fa-file-image-o','label'=>Mage::helper('adminhtml')->__('File image o')),
                array('value'=>'fa-file-pdf-o','label'=>Mage::helper('adminhtml')->__('File pdf o')),
                array('value'=>'fa-file-powerpoint-o','label'=>Mage::helper('adminhtml')->__('File powerpoint o')),
                array('value'=>'fa-file-video-o','label'=>Mage::helper('adminhtml')->__('File video o')),
                array('value'=>'fa-file-word-o','label'=>Mage::helper('adminhtml')->__('File word o')),
                array('value'=>'fa-film','label'=>Mage::helper('adminhtml')->__('Film')),
                array('value'=>'fa-filter','label'=>Mage::helper('adminhtml')->__('Filter')),
                array('value'=>'fa-fire','label'=>Mage::helper('adminhtml')->__('Fire')),
                array('value'=>'fa-fire-extinguisher','label'=>Mage::helper('adminhtml')->__('Fire extinguisher')),
                array('value'=>'fa-flag','label'=>Mage::helper('adminhtml')->__('Flag')),
                array('value'=>'fa-flag-checkered','label'=>Mage::helper('adminhtml')->__('Flag checkered')),
                array('value'=>'fa-flag-o','label'=>Mage::helper('adminhtml')->__('Flag o')),
                array('value'=>'fa-flask','label'=>Mage::helper('adminhtml')->__('Flask')),
                array('value'=>'fa-folder','label'=>Mage::helper('adminhtml')->__('Folder')),
                array('value'=>'fa-folder-o','label'=>Mage::helper('adminhtml')->__('Folder o')),
                array('value'=>'fa-folder-open','label'=>Mage::helper('adminhtml')->__('Folder open')),
                array('value'=>'fa-folder-open-o','label'=>Mage::helper('adminhtml')->__('Folder open o')),
                array('value'=>'fa-frown-o','label'=>Mage::helper('adminhtml')->__('Frown o')),
                array('value'=>'fa-gamepad','label'=>Mage::helper('adminhtml')->__('Gamepad')),
                array('value'=>'fa-gavel','label'=>Mage::helper('adminhtml')->__('Gavel')),
                array('value'=>'fa-gift','label'=>Mage::helper('adminhtml')->__('Gift')),
                array('value'=>'fa-glass','label'=>Mage::helper('adminhtml')->__('Glass')),
                array('value'=>'fa-globe','label'=>Mage::helper('adminhtml')->__('Globe')),
                array('value'=>'fa-graduation-cap','label'=>Mage::helper('adminhtml')->__('Graduation cap')),
                array('value'=>'fa-hdd-o','label'=>Mage::helper('adminhtml')->__('Hdd o')),
                array('value'=>'fa-headphones','label'=>Mage::helper('adminhtml')->__('Headphones')),
                array('value'=>'fa-heart','label'=>Mage::helper('adminhtml')->__('Heart')),
                array('value'=>'fa-heart-o','label'=>Mage::helper('adminhtml')->__('Heart o')),
                array('value'=>'fa-history','label'=>Mage::helper('adminhtml')->__('History')),
                array('value'=>'fa-home','label'=>Mage::helper('adminhtml')->__('Home')),
                array('value'=>'fa-inbox','label'=>Mage::helper('adminhtml')->__('Inbox')),
                array('value'=>'fa-info','label'=>Mage::helper('adminhtml')->__('Info')),
                array('value'=>'fa-info-circle','label'=>Mage::helper('adminhtml')->__('Info circle')),
                array('value'=>'fa-key','label'=>Mage::helper('adminhtml')->__('Key')),
                array('value'=>'fa-keyboard-o','label'=>Mage::helper('adminhtml')->__('Keyboard o')),
                array('value'=>'fa-language','label'=>Mage::helper('adminhtml')->__('Language')),
                array('value'=>'fa-laptop','label'=>Mage::helper('adminhtml')->__('Laptop')),
                array('value'=>'fa-leaf','label'=>Mage::helper('adminhtml')->__('Leaf')),
                array('value'=>'fa-lemon-o','label'=>Mage::helper('adminhtml')->__('Lemon o')),
                array('value'=>'fa-level-down','label'=>Mage::helper('adminhtml')->__('Level down')),
                array('value'=>'fa-level-up','label'=>Mage::helper('adminhtml')->__('Level up')),
                array('value'=>'fa-life-ring','label'=>Mage::helper('adminhtml')->__('Life ring')),
                array('value'=>'fa-lightbulb-o','label'=>Mage::helper('adminhtml')->__('Lightbulb o')),
                array('value'=>'fa-location-arrow','label'=>Mage::helper('adminhtml')->__('Location arrow')),
                array('value'=>'fa-lock','label'=>Mage::helper('adminhtml')->__('Lock')),
                array('value'=>'fa-magic','label'=>Mage::helper('adminhtml')->__('Magic')),
                array('value'=>'fa-magnet','label'=>Mage::helper('adminhtml')->__('Magnet')),
                array('value'=>'fa-male','label'=>Mage::helper('adminhtml')->__('Male')),
                array('value'=>'fa-map-marker','label'=>Mage::helper('adminhtml')->__('Map marker')),
                array('value'=>'fa-meh-o','label'=>Mage::helper('adminhtml')->__('Meh o')),
                array('value'=>'fa-microphone','label'=>Mage::helper('adminhtml')->__('Microphone')),
                array('value'=>'fa-microphone-slash','label'=>Mage::helper('adminhtml')->__('Microphone slash')),
                array('value'=>'fa-minus','label'=>Mage::helper('adminhtml')->__('Minus')),
                array('value'=>'fa-minus-circle','label'=>Mage::helper('adminhtml')->__('Minus circle')),
                array('value'=>'fa-minus-square','label'=>Mage::helper('adminhtml')->__('Minus square')),
                array('value'=>'fa-minus-square-o','label'=>Mage::helper('adminhtml')->__('Minus square o')),
                array('value'=>'fa-mobile','label'=>Mage::helper('adminhtml')->__('Mobile')),
                array('value'=>'fa-money','label'=>Mage::helper('adminhtml')->__('Money')),
                array('value'=>'fa-moon-o','label'=>Mage::helper('adminhtml')->__('Moon o')),
                array('value'=>'fa-music','label'=>Mage::helper('adminhtml')->__('Music')),
                array('value'=>'fa-paper-plane','label'=>Mage::helper('adminhtml')->__('Paper plane')),
                array('value'=>'fa-paper-plane-o','label'=>Mage::helper('adminhtml')->__('Paper plane o')),
                array('value'=>'fa-paw','label'=>Mage::helper('adminhtml')->__('Paw')),
                array('value'=>'fa-pencil','label'=>Mage::helper('adminhtml')->__('Pencil')),
                array('value'=>'fa-pencil-square','label'=>Mage::helper('adminhtml')->__('Pencil square')),
                array('value'=>'fa-pencil-square-o','label'=>Mage::helper('adminhtml')->__('Pencil square o')),
                array('value'=>'fa-phone','label'=>Mage::helper('adminhtml')->__('Phone')),
                array('value'=>'fa-phone-square','label'=>Mage::helper('adminhtml')->__('Phone square')),
                array('value'=>'fa-picture-o','label'=>Mage::helper('adminhtml')->__('Picture o')),
                array('value'=>'fa-plane','label'=>Mage::helper('adminhtml')->__('Plane')),
                array('value'=>'fa-plus','label'=>Mage::helper('adminhtml')->__('Plus')),
                array('value'=>'fa-plus-circle','label'=>Mage::helper('adminhtml')->__('Plus circle')),
                array('value'=>'fa-plus-square','label'=>Mage::helper('adminhtml')->__('Plus square')),
                array('value'=>'fa-plus-square-o','label'=>Mage::helper('adminhtml')->__('Plus square o')),
                array('value'=>'fa-power-off','label'=>Mage::helper('adminhtml')->__('Power off')),
                array('value'=>'fa-print','label'=>Mage::helper('adminhtml')->__('Print')),
                array('value'=>'fa-puzzle-piece','label'=>Mage::helper('adminhtml')->__('Puzzle piece')),
                array('value'=>'fa-qrcode','label'=>Mage::helper('adminhtml')->__('Qrcode')),
                array('value'=>'fa-question','label'=>Mage::helper('adminhtml')->__('Question')),
                array('value'=>'fa-question-circle','label'=>Mage::helper('adminhtml')->__('Question circle')),
                array('value'=>'fa-quote-left','label'=>Mage::helper('adminhtml')->__('Quote left')),
                array('value'=>'fa-quote-right','label'=>Mage::helper('adminhtml')->__('Quote right')),
                array('value'=>'fa-random','label'=>Mage::helper('adminhtml')->__('Random')),
                array('value'=>'fa-recycle','label'=>Mage::helper('adminhtml')->__('Recycle')),
                array('value'=>'fa-refresh','label'=>Mage::helper('adminhtml')->__('Refresh')),
                array('value'=>'fa-reply','label'=>Mage::helper('adminhtml')->__('Reply')),
                array('value'=>'fa-reply-all','label'=>Mage::helper('adminhtml')->__('Reply all')),
                array('value'=>'fa-retweet','label'=>Mage::helper('adminhtml')->__('Retweet')),
                array('value'=>'fa-road','label'=>Mage::helper('adminhtml')->__('Road')),
                array('value'=>'fa-rocket','label'=>Mage::helper('adminhtml')->__('Rocket')),
                array('value'=>'fa-rss','label'=>Mage::helper('adminhtml')->__('Rss')),
                array('value'=>'fa-rss-square','label'=>Mage::helper('adminhtml')->__('Rss square')),
                array('value'=>'fa-search','label'=>Mage::helper('adminhtml')->__('Search')),
                array('value'=>'fa-search-minus','label'=>Mage::helper('adminhtml')->__('Search minus')),
                array('value'=>'fa-search-plus','label'=>Mage::helper('adminhtml')->__('Search plus')),
                array('value'=>'fa-share','label'=>Mage::helper('adminhtml')->__('Share')),
                array('value'=>'fa-share-alt','label'=>Mage::helper('adminhtml')->__('Share alt')),
                array('value'=>'fa-share-alt-square','label'=>Mage::helper('adminhtml')->__('Share alt square')),
                array('value'=>'fa-share-square','label'=>Mage::helper('adminhtml')->__('Share square')),
                array('value'=>'fa-share-square-o','label'=>Mage::helper('adminhtml')->__('Share square o')),
                array('value'=>'fa-shield','label'=>Mage::helper('adminhtml')->__('Shield')),
                array('value'=>'fa-shopping-cart','label'=>Mage::helper('adminhtml')->__('Shopping cart')),
                array('value'=>'fa-sign-in','label'=>Mage::helper('adminhtml')->__('Sign in')),
                array('value'=>'fa-sign-out','label'=>Mage::helper('adminhtml')->__('Sign out')),
                array('value'=>'fa-signal','label'=>Mage::helper('adminhtml')->__('Signal')),
                array('value'=>'fa-sitemap','label'=>Mage::helper('adminhtml')->__('Sitemap')),
                array('value'=>'fa-sliders','label'=>Mage::helper('adminhtml')->__('Sliders')),
                array('value'=>'fa-smile-o','label'=>Mage::helper('adminhtml')->__('Smile o')),
                array('value'=>'fa-sort','label'=>Mage::helper('adminhtml')->__('Sort')),
                array('value'=>'fa-sort-alpha-asc','label'=>Mage::helper('adminhtml')->__('Sort alpha asc')),
                array('value'=>'fa-sort-alpha-desc','label'=>Mage::helper('adminhtml')->__('Sort alpha desc')),
                array('value'=>'fa-sort-amount-asc','label'=>Mage::helper('adminhtml')->__('Sort amount asc')),
                array('value'=>'fa-sort-amount-desc','label'=>Mage::helper('adminhtml')->__('Sort amount desc')),
                array('value'=>'fa-sort-asc','label'=>Mage::helper('adminhtml')->__('Sort asc')),
                array('value'=>'fa-sort-desc','label'=>Mage::helper('adminhtml')->__('Sort desc')),
                array('value'=>'fa-sort-numeric-asc','label'=>Mage::helper('adminhtml')->__('Sort numeric asc')),
                array('value'=>'fa-sort-numeric-desc','label'=>Mage::helper('adminhtml')->__('Sort numeric desc')),
                array('value'=>'fa-space-shuttle','label'=>Mage::helper('adminhtml')->__('Space shuttle')),
                array('value'=>'fa-spinner','label'=>Mage::helper('adminhtml')->__('Spinner')),
                array('value'=>'fa-spoon','label'=>Mage::helper('adminhtml')->__('Spoon')),
                array('value'=>'fa-square','label'=>Mage::helper('adminhtml')->__('Square')),
                array('value'=>'fa-square-o','label'=>Mage::helper('adminhtml')->__('Square o')),
                array('value'=>'fa-star','label'=>Mage::helper('adminhtml')->__('Star')),
                array('value'=>'fa-star-half','label'=>Mage::helper('adminhtml')->__('Star half')),
                array('value'=>'fa-star-half-o','label'=>Mage::helper('adminhtml')->__('Star half o')),
                array('value'=>'fa-star-o','label'=>Mage::helper('adminhtml')->__('Star o')),
                array('value'=>'fa-suitcase','label'=>Mage::helper('adminhtml')->__('Suitcase')),
                array('value'=>'fa-sun-o','label'=>Mage::helper('adminhtml')->__('Sun o')),
                array('value'=>'fa-tablet','label'=>Mage::helper('adminhtml')->__('Tablet')),
                array('value'=>'fa-tachometer','label'=>Mage::helper('adminhtml')->__('Tachometer')),
                array('value'=>'fa-tag','label'=>Mage::helper('adminhtml')->__('Tag')),
                array('value'=>'fa-tags','label'=>Mage::helper('adminhtml')->__('Tags')),
                array('value'=>'fa-tasks','label'=>Mage::helper('adminhtml')->__('Tasks')),
                array('value'=>'fa-taxi','label'=>Mage::helper('adminhtml')->__('Taxi')),
                array('value'=>'fa-terminal','label'=>Mage::helper('adminhtml')->__('Terminal')),
                array('value'=>'fa-thumb-tack','label'=>Mage::helper('adminhtml')->__('Thumb tack')),
                array('value'=>'fa-thumbs-down','label'=>Mage::helper('adminhtml')->__('Thumbs down')),
                array('value'=>'fa-thumbs-o-down','label'=>Mage::helper('adminhtml')->__('Thumbs o down')),
                array('value'=>'fa-thumbs-o-up','label'=>Mage::helper('adminhtml')->__('Thumbs o up')),
                array('value'=>'fa-thumbs-up','label'=>Mage::helper('adminhtml')->__('Thumbs up')),
                array('value'=>'fa-ticket','label'=>Mage::helper('adminhtml')->__('Ticket')),
                array('value'=>'fa-times','label'=>Mage::helper('adminhtml')->__('Times')),
                array('value'=>'fa-times-circle','label'=>Mage::helper('adminhtml')->__('Times circle')),
                array('value'=>'fa-times-circle-o','label'=>Mage::helper('adminhtml')->__('Times circle o')),
                array('value'=>'fa-tint','label'=>Mage::helper('adminhtml')->__('Tint')),
                array('value'=>'fa-trash-o','label'=>Mage::helper('adminhtml')->__('Trash o')),
                array('value'=>'fa-tree','label'=>Mage::helper('adminhtml')->__('Tree')),
                array('value'=>'fa-trophy','label'=>Mage::helper('adminhtml')->__('Trophy')),
                array('value'=>'fa-truck','label'=>Mage::helper('adminhtml')->__('Truck')),
                array('value'=>'fa-umbrella','label'=>Mage::helper('adminhtml')->__('Umbrella')),
                array('value'=>'fa-university','label'=>Mage::helper('adminhtml')->__('University')),
                array('value'=>'fa-unlock','label'=>Mage::helper('adminhtml')->__('Unlock')),
                array('value'=>'fa-unlock-alt','label'=>Mage::helper('adminhtml')->__('Unlock alt')),
                array('value'=>'fa-upload','label'=>Mage::helper('adminhtml')->__('Upload')),
                array('value'=>'fa-user','label'=>Mage::helper('adminhtml')->__('User')),
                array('value'=>'fa-users','label'=>Mage::helper('adminhtml')->__('Users')),
                array('value'=>'fa-video-camera','label'=>Mage::helper('adminhtml')->__('Video camera')),
                array('value'=>'fa-volume-down','label'=>Mage::helper('adminhtml')->__('Volume down')),
                array('value'=>'fa-volume-off','label'=>Mage::helper('adminhtml')->__('Volume off')),
                array('value'=>'fa-volume-up','label'=>Mage::helper('adminhtml')->__('Volume up')),
                array('value'=>'fa-wheelchair','label'=>Mage::helper('adminhtml')->__('Wheelchair')),
                array('value'=>'fa-wrench','label'=>Mage::helper('adminhtml')->__('Wrench')),
                array('value'=>'fa-file','label'=>Mage::helper('adminhtml')->__('File')),
                array('value'=>'fa-file-archive-o','label'=>Mage::helper('adminhtml')->__('File archive o')),
                array('value'=>'fa-file-audio-o','label'=>Mage::helper('adminhtml')->__('File audio o')),
                array('value'=>'fa-file-code-o','label'=>Mage::helper('adminhtml')->__('File code o')),
                array('value'=>'fa-file-excel-o','label'=>Mage::helper('adminhtml')->__('File excel o')),
                array('value'=>'fa-file-image-o','label'=>Mage::helper('adminhtml')->__('File image o')),
                array('value'=>'fa-file-o','label'=>Mage::helper('adminhtml')->__('File o')),
                array('value'=>'fa-file-pdf-o','label'=>Mage::helper('adminhtml')->__('File pdf o')),
                array('value'=>'fa-file-powerpoint-o','label'=>Mage::helper('adminhtml')->__('File powerpoint o')),
                array('value'=>'fa-file-text','label'=>Mage::helper('adminhtml')->__('File text')),
                array('value'=>'fa-file-text-o','label'=>Mage::helper('adminhtml')->__('File text o')),
                array('value'=>'fa-file-video-o','label'=>Mage::helper('adminhtml')->__('File video o')),
                array('value'=>'fa-file-word-o','label'=>Mage::helper('adminhtml')->__('File word o')),
                array('value'=>'fa-circle-o-notch','label'=>Mage::helper('adminhtml')->__('Circle o notch')),
                array('value'=>'fa-cog','label'=>Mage::helper('adminhtml')->__('Cog')),
                array('value'=>'fa-refresh','label'=>Mage::helper('adminhtml')->__('Refresh')),
                array('value'=>'fa-spinner','label'=>Mage::helper('adminhtml')->__('Spinner')),
                array('value'=>'fa-check-square','label'=>Mage::helper('adminhtml')->__('Check square')),
                array('value'=>'fa-check-square-o','label'=>Mage::helper('adminhtml')->__('Check square o')),
                array('value'=>'fa-circle','label'=>Mage::helper('adminhtml')->__('Circle')),
                array('value'=>'fa-circle-o','label'=>Mage::helper('adminhtml')->__('Circle o')),
                array('value'=>'fa-dot-circle-o','label'=>Mage::helper('adminhtml')->__('Dot circle o')),
                array('value'=>'fa-minus-square','label'=>Mage::helper('adminhtml')->__('Minus square')),
                array('value'=>'fa-minus-square-o','label'=>Mage::helper('adminhtml')->__('Minus square o')),
                array('value'=>'fa-plus-square','label'=>Mage::helper('adminhtml')->__('Plus square')),
                array('value'=>'fa-plus-square-o','label'=>Mage::helper('adminhtml')->__('Plus square o')),
                array('value'=>'fa-square','label'=>Mage::helper('adminhtml')->__('Square')),
                array('value'=>'fa-square-o','label'=>Mage::helper('adminhtml')->__('Square o')),
                array('value'=>'fa-btc','label'=>Mage::helper('adminhtml')->__('Btc')),
                array('value'=>'fa-eur','label'=>Mage::helper('adminhtml')->__('Eur')),
                array('value'=>'fa-gbp','label'=>Mage::helper('adminhtml')->__('Gbp')),
                array('value'=>'fa-inr','label'=>Mage::helper('adminhtml')->__('Inr')),
                array('value'=>'fa-jpy','label'=>Mage::helper('adminhtml')->__('Jpy')),
                array('value'=>'fa-krw','label'=>Mage::helper('adminhtml')->__('Krw')),
                array('value'=>'fa-money','label'=>Mage::helper('adminhtml')->__('Money')),
                array('value'=>'fa-rub','label'=>Mage::helper('adminhtml')->__('Rub')),
                array('value'=>'fa-try','label'=>Mage::helper('adminhtml')->__('Try')),
                array('value'=>'fa-usd','label'=>Mage::helper('adminhtml')->__('Usd')),
                array('value'=>'fa-align-center','label'=>Mage::helper('adminhtml')->__('Align center')),
                array('value'=>'fa-align-justify','label'=>Mage::helper('adminhtml')->__('Align justify')),
                array('value'=>'fa-align-left','label'=>Mage::helper('adminhtml')->__('Align left')),
                array('value'=>'fa-align-right','label'=>Mage::helper('adminhtml')->__('Align right')),
                array('value'=>'fa-bold','label'=>Mage::helper('adminhtml')->__('Bold')),
                array('value'=>'fa-chain-broken','label'=>Mage::helper('adminhtml')->__('Chain broken')),
                array('value'=>'fa-clipboard','label'=>Mage::helper('adminhtml')->__('Clipboard')),
                array('value'=>'fa-columns','label'=>Mage::helper('adminhtml')->__('Columns')),
                array('value'=>'fa-eraser','label'=>Mage::helper('adminhtml')->__('Eraser')),
                array('value'=>'fa-file','label'=>Mage::helper('adminhtml')->__('File')),
                array('value'=>'fa-file-o','label'=>Mage::helper('adminhtml')->__('File o')),
                array('value'=>'fa-file-text','label'=>Mage::helper('adminhtml')->__('File text')),
                array('value'=>'fa-file-text-o','label'=>Mage::helper('adminhtml')->__('File text o')),
                array('value'=>'fa-files-o','label'=>Mage::helper('adminhtml')->__('Files o')),
                array('value'=>'fa-floppy-o','label'=>Mage::helper('adminhtml')->__('Floppy o')),
                array('value'=>'fa-font','label'=>Mage::helper('adminhtml')->__('Font')),
                array('value'=>'fa-header','label'=>Mage::helper('adminhtml')->__('Header')),
                array('value'=>'fa-indent','label'=>Mage::helper('adminhtml')->__('Indent')),
                array('value'=>'fa-italic','label'=>Mage::helper('adminhtml')->__('Italic')),
                array('value'=>'fa-link','label'=>Mage::helper('adminhtml')->__('Link')),
                array('value'=>'fa-list','label'=>Mage::helper('adminhtml')->__('List')),
                array('value'=>'fa-list-alt','label'=>Mage::helper('adminhtml')->__('List alt')),
                array('value'=>'fa-list-ol','label'=>Mage::helper('adminhtml')->__('List ol')),
                array('value'=>'fa-list-ul','label'=>Mage::helper('adminhtml')->__('List ul')),
                array('value'=>'fa-outdent','label'=>Mage::helper('adminhtml')->__('Outdent')),
                array('value'=>'fa-paperclip','label'=>Mage::helper('adminhtml')->__('Paperclip')),
                array('value'=>'fa-paragraph','label'=>Mage::helper('adminhtml')->__('Paragraph')),
                array('value'=>'fa-repeat','label'=>Mage::helper('adminhtml')->__('Repeat')),
                array('value'=>'fa-scissors','label'=>Mage::helper('adminhtml')->__('Scissors')),
                array('value'=>'fa-strikethrough','label'=>Mage::helper('adminhtml')->__('Strikethrough')),
                array('value'=>'fa-subscript','label'=>Mage::helper('adminhtml')->__('Subscript')),
                array('value'=>'fa-superscript','label'=>Mage::helper('adminhtml')->__('Superscript')),
                array('value'=>'fa-table','label'=>Mage::helper('adminhtml')->__('Table')),
                array('value'=>'fa-text-height','label'=>Mage::helper('adminhtml')->__('Text height')),
                array('value'=>'fa-text-width','label'=>Mage::helper('adminhtml')->__('Text width')),
                array('value'=>'fa-th','label'=>Mage::helper('adminhtml')->__('Th')),
                array('value'=>'fa-th-large','label'=>Mage::helper('adminhtml')->__('Th large')),
                array('value'=>'fa-th-list','label'=>Mage::helper('adminhtml')->__('Th list')),
                array('value'=>'fa-underline','label'=>Mage::helper('adminhtml')->__('Underline')),
                array('value'=>'fa-undo','label'=>Mage::helper('adminhtml')->__('Undo')),
                array('value'=>'fa-angle-double-down','label'=>Mage::helper('adminhtml')->__('Angle double down')),
                array('value'=>'fa-angle-double-left','label'=>Mage::helper('adminhtml')->__('Angle double left')),
                array('value'=>'fa-angle-double-right','label'=>Mage::helper('adminhtml')->__('Angle double right')),
                array('value'=>'fa-angle-double-up','label'=>Mage::helper('adminhtml')->__('Angle double up')),
                array('value'=>'fa-angle-down','label'=>Mage::helper('adminhtml')->__('Angle down')),
                array('value'=>'fa-angle-left','label'=>Mage::helper('adminhtml')->__('Angle left')),
                array('value'=>'fa-angle-right','label'=>Mage::helper('adminhtml')->__('Angle right')),
                array('value'=>'fa-angle-up','label'=>Mage::helper('adminhtml')->__('Angle up')),
                array('value'=>'fa-arrow-circle-down','label'=>Mage::helper('adminhtml')->__('Arrow circle down')),
                array('value'=>'fa-arrow-circle-left','label'=>Mage::helper('adminhtml')->__('Arrow circle left')),
                array('value'=>'fa-arrow-circle-o-down','label'=>Mage::helper('adminhtml')->__('Arrow circle o down')),
                array('value'=>'fa-arrow-circle-o-left','label'=>Mage::helper('adminhtml')->__('Arrow circle o left')),
                array('value'=>'fa-arrow-circle-o-right','label'=>Mage::helper('adminhtml')->__('Arrow circle o right')),
                array('value'=>'fa-arrow-circle-o-up','label'=>Mage::helper('adminhtml')->__('Arrow circle o up')),
                array('value'=>'fa-arrow-circle-right','label'=>Mage::helper('adminhtml')->__('Arrow circle right')),
                array('value'=>'fa-arrow-circle-up','label'=>Mage::helper('adminhtml')->__('Arrow circle up')),
                array('value'=>'fa-arrow-down','label'=>Mage::helper('adminhtml')->__('Arrow down')),
                array('value'=>'fa-arrow-left','label'=>Mage::helper('adminhtml')->__('Arrow left')),
                array('value'=>'fa-arrow-right','label'=>Mage::helper('adminhtml')->__('Arrow right')),
                array('value'=>'fa-arrow-up','label'=>Mage::helper('adminhtml')->__('Arrow up')),
                array('value'=>'fa-arrows','label'=>Mage::helper('adminhtml')->__('Arrows')),
                array('value'=>'fa-arrows-alt','label'=>Mage::helper('adminhtml')->__('Arrows alt')),
                array('value'=>'fa-arrows-h','label'=>Mage::helper('adminhtml')->__('Arrows h')),
                array('value'=>'fa-arrows-v','label'=>Mage::helper('adminhtml')->__('Arrows v')),
                array('value'=>'fa-caret-down','label'=>Mage::helper('adminhtml')->__('Caret down')),
                array('value'=>'fa-caret-left','label'=>Mage::helper('adminhtml')->__('Caret left')),
                array('value'=>'fa-caret-right','label'=>Mage::helper('adminhtml')->__('Caret right')),
                array('value'=>'fa-caret-square-o-down','label'=>Mage::helper('adminhtml')->__('Caret square o down')),
                array('value'=>'fa-caret-square-o-left','label'=>Mage::helper('adminhtml')->__('Caret square o left')),
                array('value'=>'fa-caret-square-o-right','label'=>Mage::helper('adminhtml')->__('Caret square o right')),
                array('value'=>'fa-caret-square-o-up','label'=>Mage::helper('adminhtml')->__('Caret square o up')),
                array('value'=>'fa-caret-up','label'=>Mage::helper('adminhtml')->__('Caret up')),
                array('value'=>'fa-chevron-circle-down','label'=>Mage::helper('adminhtml')->__('Chevron circle down')),
                array('value'=>'fa-chevron-circle-left','label'=>Mage::helper('adminhtml')->__('Chevron circle left')),
                array('value'=>'fa-chevron-circle-right','label'=>Mage::helper('adminhtml')->__('Chevron circle right')),
                array('value'=>'fa-chevron-circle-up','label'=>Mage::helper('adminhtml')->__('Chevron circle up')),
                array('value'=>'fa-chevron-down','label'=>Mage::helper('adminhtml')->__('Chevron down')),
                array('value'=>'fa-chevron-left','label'=>Mage::helper('adminhtml')->__('Chevron left')),
                array('value'=>'fa-chevron-right','label'=>Mage::helper('adminhtml')->__('Chevron right')),
                array('value'=>'fa-chevron-up','label'=>Mage::helper('adminhtml')->__('Chevron up')),
                array('value'=>'fa-hand-o-down','label'=>Mage::helper('adminhtml')->__('Hand o down')),
                array('value'=>'fa-hand-o-left','label'=>Mage::helper('adminhtml')->__('Hand o left')),
                array('value'=>'fa-hand-o-right','label'=>Mage::helper('adminhtml')->__('Hand o right')),
                array('value'=>'fa-hand-o-up','label'=>Mage::helper('adminhtml')->__('Hand o up')),
                array('value'=>'fa-long-arrow-down','label'=>Mage::helper('adminhtml')->__('Long arrow down')),
                array('value'=>'fa-long-arrow-left','label'=>Mage::helper('adminhtml')->__('Long arrow left')),
                array('value'=>'fa-long-arrow-right','label'=>Mage::helper('adminhtml')->__('Long arrow right')),
                array('value'=>'fa-long-arrow-up','label'=>Mage::helper('adminhtml')->__('Long arrow up')),
                array('value'=>'fa-arrows-alt','label'=>Mage::helper('adminhtml')->__('Arrows alt')),
                array('value'=>'fa-backward','label'=>Mage::helper('adminhtml')->__('Backward')),
                array('value'=>'fa-compress','label'=>Mage::helper('adminhtml')->__('Compress')),
                array('value'=>'fa-eject','label'=>Mage::helper('adminhtml')->__('Eject')),
                array('value'=>'fa-expand','label'=>Mage::helper('adminhtml')->__('Expand')),
                array('value'=>'fa-fast-backward','label'=>Mage::helper('adminhtml')->__('Fast backward')),
                array('value'=>'fa-fast-forward','label'=>Mage::helper('adminhtml')->__('Fast forward')),
                array('value'=>'fa-forward','label'=>Mage::helper('adminhtml')->__('Forward')),
                array('value'=>'fa-pause','label'=>Mage::helper('adminhtml')->__('Pause')),
                array('value'=>'fa-play','label'=>Mage::helper('adminhtml')->__('Play')),
                array('value'=>'fa-play-circle','label'=>Mage::helper('adminhtml')->__('Play circle')),
                array('value'=>'fa-play-circle-o','label'=>Mage::helper('adminhtml')->__('Play circle o')),
                array('value'=>'fa-step-backward','label'=>Mage::helper('adminhtml')->__('Step backward')),
                array('value'=>'fa-step-forward','label'=>Mage::helper('adminhtml')->__('Step forward')),
                array('value'=>'fa-stop','label'=>Mage::helper('adminhtml')->__('Stop')),
                array('value'=>'fa-youtube-play','label'=>Mage::helper('adminhtml')->__('Youtube play')),
                array('value'=>'fa-adn','label'=>Mage::helper('adminhtml')->__('Adn')),
                array('value'=>'fa-android','label'=>Mage::helper('adminhtml')->__('Android')),
                array('value'=>'fa-apple','label'=>Mage::helper('adminhtml')->__('Apple')),
                array('value'=>'fa-behance','label'=>Mage::helper('adminhtml')->__('Behance')),
                array('value'=>'fa-behance-square','label'=>Mage::helper('adminhtml')->__('Behance square')),
                array('value'=>'fa-bitbucket','label'=>Mage::helper('adminhtml')->__('Bitbucket')),
                array('value'=>'fa-bitbucket-square','label'=>Mage::helper('adminhtml')->__('Bitbucket square')),
                array('value'=>'fa-btc','label'=>Mage::helper('adminhtml')->__('Btc')),
                array('value'=>'fa-codepen','label'=>Mage::helper('adminhtml')->__('Codepen')),
                array('value'=>'fa-css3','label'=>Mage::helper('adminhtml')->__('Css3')),
                array('value'=>'fa-delicious','label'=>Mage::helper('adminhtml')->__('Delicious')),
                array('value'=>'fa-deviantart','label'=>Mage::helper('adminhtml')->__('Deviantart')),
                array('value'=>'fa-digg','label'=>Mage::helper('adminhtml')->__('Digg')),
                array('value'=>'fa-dribbble','label'=>Mage::helper('adminhtml')->__('Dribbble')),
                array('value'=>'fa-dropbox','label'=>Mage::helper('adminhtml')->__('Dropbox')),
                array('value'=>'fa-drupal','label'=>Mage::helper('adminhtml')->__('Drupal')),
                array('value'=>'fa-empire','label'=>Mage::helper('adminhtml')->__('Empire')),
                array('value'=>'fa-facebook','label'=>Mage::helper('adminhtml')->__('Facebook')),
                array('value'=>'fa-facebook-square','label'=>Mage::helper('adminhtml')->__('Facebook square')),
                array('value'=>'fa-flickr','label'=>Mage::helper('adminhtml')->__('Flickr')),
                array('value'=>'fa-foursquare','label'=>Mage::helper('adminhtml')->__('Foursquare')),
                array('value'=>'fa-git','label'=>Mage::helper('adminhtml')->__('Git')),
                array('value'=>'fa-git-square','label'=>Mage::helper('adminhtml')->__('Git square')),
                array('value'=>'fa-github','label'=>Mage::helper('adminhtml')->__('Github')),
                array('value'=>'fa-github-alt','label'=>Mage::helper('adminhtml')->__('Github alt')),
                array('value'=>'fa-github-square','label'=>Mage::helper('adminhtml')->__('Github square')),
                array('value'=>'fa-gittip','label'=>Mage::helper('adminhtml')->__('Gittip')),
                array('value'=>'fa-google','label'=>Mage::helper('adminhtml')->__('Google')),
                array('value'=>'fa-google-plus','label'=>Mage::helper('adminhtml')->__('Google plus')),
                array('value'=>'fa-google-plus-square','label'=>Mage::helper('adminhtml')->__('Google plus square')),
                array('value'=>'fa-hacker-news','label'=>Mage::helper('adminhtml')->__('Hacker news')),
                array('value'=>'fa-html5','label'=>Mage::helper('adminhtml')->__('Html5')),
                array('value'=>'fa-instagram','label'=>Mage::helper('adminhtml')->__('Instagram')),
                array('value'=>'fa-joomla','label'=>Mage::helper('adminhtml')->__('Joomla')),
                array('value'=>'fa-jsfiddle','label'=>Mage::helper('adminhtml')->__('Jsfiddle')),
                array('value'=>'fa-linkedin','label'=>Mage::helper('adminhtml')->__('Linkedin')),
                array('value'=>'fa-linkedin-square','label'=>Mage::helper('adminhtml')->__('Linkedin square')),
                array('value'=>'fa-linux','label'=>Mage::helper('adminhtml')->__('Linux')),
                array('value'=>'fa-maxcdn','label'=>Mage::helper('adminhtml')->__('Maxcdn')),
                array('value'=>'fa-openid','label'=>Mage::helper('adminhtml')->__('Openid')),
                array('value'=>'fa-pagelines','label'=>Mage::helper('adminhtml')->__('Pagelines')),
                array('value'=>'fa-pied-piper','label'=>Mage::helper('adminhtml')->__('Pied piper')),
                array('value'=>'fa-pied-piper-alt','label'=>Mage::helper('adminhtml')->__('Pied piper alt')),
                array('value'=>'fa-pinterest','label'=>Mage::helper('adminhtml')->__('Pinterest')),
                array('value'=>'fa-pinterest-square','label'=>Mage::helper('adminhtml')->__('Pinterest square')),
                array('value'=>'fa-qq','label'=>Mage::helper('adminhtml')->__('Qq')),
                array('value'=>'fa-rebel','label'=>Mage::helper('adminhtml')->__('Rebel')),
                array('value'=>'fa-reddit','label'=>Mage::helper('adminhtml')->__('Reddit')),
                array('value'=>'fa-reddit-square','label'=>Mage::helper('adminhtml')->__('Reddit square')),
                array('value'=>'fa-renren','label'=>Mage::helper('adminhtml')->__('Renren')),
                array('value'=>'fa-share-alt','label'=>Mage::helper('adminhtml')->__('Share alt')),
                array('value'=>'fa-share-alt-square','label'=>Mage::helper('adminhtml')->__('Share alt square')),
                array('value'=>'fa-skype','label'=>Mage::helper('adminhtml')->__('Skype')),
                array('value'=>'fa-slack','label'=>Mage::helper('adminhtml')->__('Slack')),
                array('value'=>'fa-soundcloud','label'=>Mage::helper('adminhtml')->__('Soundcloud')),
                array('value'=>'fa-spotify','label'=>Mage::helper('adminhtml')->__('Spotify')),
                array('value'=>'fa-stack-exchange','label'=>Mage::helper('adminhtml')->__('Stack exchange')),
                array('value'=>'fa-stack-overflow','label'=>Mage::helper('adminhtml')->__('Stack overflow')),
                array('value'=>'fa-steam','label'=>Mage::helper('adminhtml')->__('Steam')),
                array('value'=>'fa-steam-square','label'=>Mage::helper('adminhtml')->__('Steam square')),
                array('value'=>'fa-stumbleupon','label'=>Mage::helper('adminhtml')->__('Stumbleupon')),
                array('value'=>'fa-stumbleupon-circle','label'=>Mage::helper('adminhtml')->__('Stumbleupon circle')),
                array('value'=>'fa-tencent-weibo','label'=>Mage::helper('adminhtml')->__('Tencent weibo')),
                array('value'=>'fa-trello','label'=>Mage::helper('adminhtml')->__('Trello')),
                array('value'=>'fa-tumblr','label'=>Mage::helper('adminhtml')->__('Tumblr')),
                array('value'=>'fa-tumblr-square','label'=>Mage::helper('adminhtml')->__('Tumblr square')),
                array('value'=>'fa-twitter','label'=>Mage::helper('adminhtml')->__('Twitter')),
                array('value'=>'fa-twitter-square','label'=>Mage::helper('adminhtml')->__('Twitter square')),
                array('value'=>'fa-vimeo-square','label'=>Mage::helper('adminhtml')->__('Vimeo square')),
                array('value'=>'fa-vine','label'=>Mage::helper('adminhtml')->__('Vine')),
                array('value'=>'fa-vk','label'=>Mage::helper('adminhtml')->__('Vk')),
                array('value'=>'fa-weibo','label'=>Mage::helper('adminhtml')->__('Weibo')),
                array('value'=>'fa-weixin','label'=>Mage::helper('adminhtml')->__('Weixin')),
                array('value'=>'fa-windows','label'=>Mage::helper('adminhtml')->__('Windows')),
                array('value'=>'fa-wordpress','label'=>Mage::helper('adminhtml')->__('Wordpress')),
                array('value'=>'fa-xing','label'=>Mage::helper('adminhtml')->__('Xing')),
                array('value'=>'fa-xing-square','label'=>Mage::helper('adminhtml')->__('Xing square')),
                array('value'=>'fa-yahoo','label'=>Mage::helper('adminhtml')->__('Yahoo')),
                array('value'=>'fa-youtube','label'=>Mage::helper('adminhtml')->__('Youtube')),
                array('value'=>'fa-youtube-play','label'=>Mage::helper('adminhtml')->__('Youtube play')),
                array('value'=>'fa-youtube-square','label'=>Mage::helper('adminhtml')->__('Youtube square')),
                array('value'=>'fa-ambulance','label'=>Mage::helper('adminhtml')->__('Ambulance')),
                array('value'=>'fa-h-square','label'=>Mage::helper('adminhtml')->__('H square')),
                array('value'=>'fa-hospital-o','label'=>Mage::helper('adminhtml')->__('Hospital o')),
                array('value'=>'fa-medkit','label'=>Mage::helper('adminhtml')->__('Medkit')),
                array('value'=>'fa-plus-square','label'=>Mage::helper('adminhtml')->__('Plus square')),
                array('value'=>'fa-stethoscope','label'=>Mage::helper('adminhtml')->__('Stethoscope')),
                array('value'=>'fa-user-md','label'=>Mage::helper('adminhtml')->__('User md')),
                array('value'=>'fa-wheelchair','label'=>Mage::helper('adminhtml')->__('Wheelchair')),
/// ElegantIcons

                array('value'=>'arrow_up','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Up')),
                array('value'=>'arrow_down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Down')),
                array('value'=>'arrow_left','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left')),
                array('value'=>'arrow_right','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Right')),
                array('value'=>'arrow_left-up','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Up')),
                array('value'=>'arrow_right-up','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Right Up')),
                array('value'=>'arrow_right-down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Right Down')),
                array('value'=>'arrow_left-down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Down')),
                array('value'=>'arrow-up-down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Up Down')),
                array('value'=>'arrow_up-down_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Up Down Alt')),
                array('value'=>'arrow_left-right_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Right Alt')),
                array('value'=>'arrow_left-right','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Right')),
                array('value'=>'arrow_expand_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Expand Alt 2')),
                array('value'=>'arrow_expand_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Expand Alt')),
                array('value'=>'arrow_condense','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Condense')),
                array('value'=>'arrow_expand','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Expand')),
                array('value'=>'arrow_move','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Move')),
                array('value'=>'arrow_carrot-up','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Up')),
                array('value'=>'arrow_carrot-down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Down')),
                array('value'=>'arrow_carrot-left','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Left')),
                array('value'=>'arrow_carrot-right','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Right')),
                array('value'=>'arrow_carrot-2up','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Up')),
                array('value'=>'arrow_carrot-2down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Down')),
                array('value'=>'arrow_carrot-2left','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Left')),
                array('value'=>'arrow_carrot-2right','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Right')),
                array('value'=>'arrow_carrot-up_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Up Alt 2')),
                array('value'=>'arrow_carrot-down_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Down Alt 2')),
                array('value'=>'arrow_carrot-left_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Left Alt 2')),
                array('value'=>'arrow_carrot-right_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Right Alt 2')),
                array('value'=>'arrow_carrot-2up_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Up Alt 2')),
                array('value'=>'arrow_carrot-2down_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Down Alt 2')),
                array('value'=>'arrow_carrot-2left_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Left Alt 2')),
                array('value'=>'arrow_carrot-2right_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Right Alt 2')),
                array('value'=>'arrow_triangle-up','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Up')),
                array('value'=>'arrow_triangle-down','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Down')),
                array('value'=>'arrow_triangle-left','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Left')),
                array('value'=>'arrow_triangle-right','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Right')),
                array('value'=>'arrow_triangle-up_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Up Alt 2')),
                array('value'=>'arrow_triangle-down_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Down Alt 2')),
                array('value'=>'arrow_triangle-left_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Left Alt 2')),
                array('value'=>'arrow_triangle-right_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Right Alt 2')),
                array('value'=>'arrow_back','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Back')),
                array('value'=>'icon_minus-06','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Minus 06')),
                array('value'=>'icon_plus','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Plus')),
                array('value'=>'icon_close','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Close')),
                array('value'=>'icon_check','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Check')),
                array('value'=>'icon_minus_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Minus Alt 2')),
                array('value'=>'icon_plus_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Plus Alt 2')),
                array('value'=>'icon_close_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Close Alt 2')),
                array('value'=>'icon_check_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Check Alt 2')),
                array('value'=>'icon_zoom-out_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Zoom Out Alt')),
                array('value'=>'icon_zoom-in_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Zoom In Alt')),
                array('value'=>'icon_search','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Search')),
                array('value'=>'icon_box-empty','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Box Empty')),
                array('value'=>'icon_box-selected','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Box Selected')),
                array('value'=>'icon_minus-box','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Minus Box')),
                array('value'=>'icon_plus-box','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Plus Box')),
                array('value'=>'icon_box-checked','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Box Checked')),
                array('value'=>'icon_circle-empty','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Circle Empty')),
                array('value'=>'icon_circle-slelected','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Circle Slelected')),
                array('value'=>'icon_stop_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Stop Alt 2')),
                array('value'=>'icon_stop','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Stop')),
                array('value'=>'icon_pause_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pause Alt 2')),
                array('value'=>'icon_pause','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pause')),
                array('value'=>'icon_menu','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Menu')),
                array('value'=>'icon_menu-square_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Menu Square Alt 2')),
                array('value'=>'icon_menu-circle_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Menu Circle Alt 2')),
                array('value'=>'icon_ul','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Ul')),
                array('value'=>'icon_ol','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Ol')),
                array('value'=>'icon_adjust-horiz','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Adjust Horiz')),
                array('value'=>'icon_adjust-vert','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Adjust Vert')),
                array('value'=>'icon_document_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Document Alt')),
                array('value'=>'icon_documents_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Documents Alt')),
                array('value'=>'icon_pencil','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pencil')),
                array('value'=>'icon_pencil-edit_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pencil Edit Alt')),
                array('value'=>'icon_pencil-edit','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pencil Edit')),
                array('value'=>'icon_folder-alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Alt')),
                array('value'=>'icon_folder-open_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Open Alt')),
                array('value'=>'icon_folder-add_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Add Alt')),
                array('value'=>'icon_info_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Info Alt')),
                array('value'=>'icon_error-oct_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Error Oct Alt')),
                array('value'=>'icon_error-circle_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Error Circle Alt')),
                array('value'=>'icon_error-triangle_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Error Triangle Alt')),
                array('value'=>'icon_question_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Question Alt 2')),
                array('value'=>'icon_question','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Question')),
                array('value'=>'icon_comment_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Comment Alt')),
                array('value'=>'icon_chat_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Chat Alt')),
                array('value'=>'icon_vol-mute_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Vol Mute Alt')),
                array('value'=>'icon_volume-low_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Volume Low Alt')),
                array('value'=>'icon_volume-high_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Volume High Alt')),
                array('value'=>'icon_quotations','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Quotations')),
                array('value'=>'icon_quotations_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Quotations Alt 2')),
                array('value'=>'icon_clock_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Clock Alt')),
                array('value'=>'icon_lock_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lock Alt')),
                array('value'=>'icon_lock-open_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lock Open Alt')),
                array('value'=>'icon_key_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Key Alt')),
                array('value'=>'icon_cloud_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cloud Alt')),
                array('value'=>'icon_cloud-upload_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cloud Upload Alt')),
                array('value'=>'icon_cloud-download_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cloud Download Alt')),
                array('value'=>'icon_image','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Image')),
                array('value'=>'icon_images','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Images')),
                array('value'=>'icon_lightbulb_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lightbulb Alt')),
                array('value'=>'icon_gift_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Gift Alt')),
                array('value'=>'icon_house_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon House Alt')),
                array('value'=>'icon_genius','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Genius')),
                array('value'=>'icon_mobile','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mobile')),
                array('value'=>'icon_tablet','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tablet')),
                array('value'=>'icon_laptop','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Laptop')),
                array('value'=>'icon_desktop','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Desktop')),
                array('value'=>'icon_camera_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Camera Alt')),
                array('value'=>'icon_mail_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mail Alt')),
                array('value'=>'icon_cone_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cone Alt')),
                array('value'=>'icon_ribbon_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Ribbon Alt')),
                array('value'=>'icon_bag_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Bag Alt')),
                array('value'=>'icon_creditcard','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Creditcard')),
                array('value'=>'icon_cart_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cart Alt')),
                array('value'=>'icon_paperclip','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Paperclip')),
                array('value'=>'icon_tag_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tag Alt')),
                array('value'=>'icon_tags_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tags Alt')),
                array('value'=>'icon_trash_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Trash Alt')),
                array('value'=>'icon_cursor_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cursor Alt')),
                array('value'=>'icon_mic_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mic Alt')),
                array('value'=>'icon_compass_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Compass Alt')),
                array('value'=>'icon_pin_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pin Alt')),
                array('value'=>'icon_pushpin_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pushpin Alt')),
                array('value'=>'icon_map_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Map Alt')),
                array('value'=>'icon_drawer_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Drawer Alt')),
                array('value'=>'icon_toolbox_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Toolbox Alt')),
                array('value'=>'icon_book_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Book Alt')),
                array('value'=>'icon_calendar','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Calendar')),
                array('value'=>'icon_film','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Film')),
                array('value'=>'icon_table','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Table')),
                array('value'=>'icon_contacts_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Contacts Alt')),
                array('value'=>'icon_headphones','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Headphones')),
                array('value'=>'icon_lifesaver','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lifesaver')),
                array('value'=>'icon_piechart','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Piechart')),
                array('value'=>'icon_refresh','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Refresh')),
                array('value'=>'icon_link_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Link Alt')),
                array('value'=>'icon_link','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Link')),
                array('value'=>'icon_loading','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Loading')),
                array('value'=>'icon_blocked','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Blocked')),
                array('value'=>'icon_archive_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Archive Alt')),
                array('value'=>'icon_heart_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Heart Alt')),
                array('value'=>'icon_star_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Star Alt')),
                array('value'=>'icon_star-half_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Star Half Alt')),
                array('value'=>'icon_star','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Star')),
                array('value'=>'icon_star-half','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Star Half')),
                array('value'=>'icon_tools','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tools')),
                array('value'=>'icon_tool','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tool')),
                array('value'=>'icon_cog','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cog')),
                array('value'=>'icon_cogs','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cogs')),
                array('value'=>'arrow_up_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Up Alt')),
                array('value'=>'arrow_down_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Down Alt')),
                array('value'=>'arrow_left_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Alt')),
                array('value'=>'arrow_right_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Right Alt')),
                array('value'=>'arrow_left-up_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Up Alt')),
                array('value'=>'arrow_right-up_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Right Up Alt')),
                array('value'=>'arrow_right-down_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Right Down Alt')),
                array('value'=>'arrow_left-down_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Left Down Alt')),
                array('value'=>'arrow_condense_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Condense Alt')),
                array('value'=>'arrow_expand_alt3','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Expand Alt3')),
                array('value'=>'arrow_carrot_up_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Up Alt')),
                array('value'=>'arrow_carrot-down_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Down Alt')),
                array('value'=>'arrow_carrot-left_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Left Alt')),
                array('value'=>'arrow_carrot-right_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot Right Alt')),
                array('value'=>'arrow_carrot-2up_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Up Alt')),
                array('value'=>'arrow_carrot-2dwnn_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Dwnn Alt')),
                array('value'=>'arrow_carrot-2left_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Left Alt')),
                array('value'=>'arrow_carrot-2right_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Carrot 2 Right Alt')),
                array('value'=>'arrow_triangle-up_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Up Alt')),
                array('value'=>'arrow_triangle-down_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Down Alt')),
                array('value'=>'arrow_triangle-left_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Left Alt')),
                array('value'=>'arrow_triangle-right_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Arrow Triangle Right Alt')),
                array('value'=>'icon_minus_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Minus Alt')),
                array('value'=>'icon_plus_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Plus Alt')),
                array('value'=>'icon_close_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Close Alt')),
                array('value'=>'icon_check_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Check Alt')),
                array('value'=>'icon_zoom-out','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Zoom Out')),
                array('value'=>'icon_zoom-in','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Zoom In')),
                array('value'=>'icon_stop_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Stop Alt')),
                array('value'=>'icon_menu-square_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Menu Square Alt')),
                array('value'=>'icon_menu-circle_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Menu Circle Alt')),
                array('value'=>'icon_document','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Document')),
                array('value'=>'icon_documents','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Documents')),
                array('value'=>'icon_pencil_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pencil Alt')),
                array('value'=>'icon_folder','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder')),
                array('value'=>'icon_folder-open','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Open')),
                array('value'=>'icon_folder-add','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Add')),
                array('value'=>'icon_folder_upload','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Upload')),
                array('value'=>'icon_folder_download','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Folder Download')),
                array('value'=>'icon_info','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Info')),
                array('value'=>'icon_error-circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Error Circle')),
                array('value'=>'icon_error-oct','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Error Oct')),
                array('value'=>'icon_error-triangle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Error Triangle')),
                array('value'=>'icon_question_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Question Alt')),
                array('value'=>'icon_comment','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Comment')),
                array('value'=>'icon_chat','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Chat')),
                array('value'=>'icon_vol-mute','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Vol Mute')),
                array('value'=>'icon_volume-low','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Volume Low')),
                array('value'=>'icon_volume-high','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Volume High')),
                array('value'=>'icon_quotations_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Quotations Alt')),
                array('value'=>'icon_clock','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Clock')),
                array('value'=>'icon_lock','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lock')),
                array('value'=>'icon_lock-open','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lock Open')),
                array('value'=>'icon_key','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Key')),
                array('value'=>'icon_cloud','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cloud')),
                array('value'=>'icon_cloud-upload','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cloud Upload')),
                array('value'=>'icon_cloud-download','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cloud Download')),
                array('value'=>'icon_lightbulb','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Lightbulb')),
                array('value'=>'icon_gift','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Gift')),
                array('value'=>'icon_house','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon House')),
                array('value'=>'icon_camera','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Camera')),
                array('value'=>'icon_mail','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mail')),
                array('value'=>'icon_cone','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cone')),
                array('value'=>'icon_ribbon','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Ribbon')),
                array('value'=>'icon_bag','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Bag')),
                array('value'=>'icon_cart','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cart')),
                array('value'=>'icon_tag','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tag')),
                array('value'=>'icon_tags','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Tags')),
                array('value'=>'icon_trash','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Trash')),
                array('value'=>'icon_cursor','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Cursor')),
                array('value'=>'icon_mic','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mic')),
                array('value'=>'icon_compass','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Compass')),
                array('value'=>'icon_pin','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pin')),
                array('value'=>'icon_pushpin','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pushpin')),
                array('value'=>'icon_map','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Map')),
                array('value'=>'icon_drawer','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Drawer')),
                array('value'=>'icon_toolbox','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Toolbox')),
                array('value'=>'icon_book','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Book')),
                array('value'=>'icon_contacts','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Contacts')),
                array('value'=>'icon_archive','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Archive')),
                array('value'=>'icon_heart','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Heart')),
                array('value'=>'icon_profile','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Profile')),
                array('value'=>'icon_group','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Group')),
                array('value'=>'icon_grid-2x2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Grid 2 X 2')),
                array('value'=>'icon_grid-3x3','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Grid 3x3')),
                array('value'=>'icon_music','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Music')),
                array('value'=>'icon_pause_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pause Alt')),
                array('value'=>'icon_phone','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Phone')),
                array('value'=>'icon_upload','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Upload')),
                array('value'=>'icon_download','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Download')),
                array('value'=>'social_facebook','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Facebook')),
                array('value'=>'social_twitter','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Twitter')),
                array('value'=>'social_pinterest','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Pinterest')),
                array('value'=>'social_googleplus','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Googleplus')),
                array('value'=>'social_tumblr','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Tumblr')),
                array('value'=>'social_tumbleupon','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Tumbleupon')),
                array('value'=>'social_wordpress','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Wordpress')),
                array('value'=>'social_instagram','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Instagram')),
                array('value'=>'social_dribbble','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Dribbble')),
                array('value'=>'social_vimeo','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Vimeo')),
                array('value'=>'social_linkedin','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Linkedin')),
                array('value'=>'social_rss','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Rss')),
                array('value'=>'social_deviantart','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Deviantart')),
                array('value'=>'social_share','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Share')),
                array('value'=>'social_myspace','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Myspace')),
                array('value'=>'social_skype','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Skype')),
                array('value'=>'social_youtube','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Youtube')),
                array('value'=>'social_picassa','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Picassa')),
                array('value'=>'social_googledrive','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Googledrive')),
                array('value'=>'social_flickr','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Flickr')),
                array('value'=>'social_blogger','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Blogger')),
                array('value'=>'social_spotify','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Spotify')),
                array('value'=>'social_delicious','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Delicious')),
                array('value'=>'social_facebook_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Facebook Circle')),
                array('value'=>'social_twitter_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Twitter Circle')),
                array('value'=>'social_pinterest_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Pinterest Circle')),
                array('value'=>'social_googleplus_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Googleplus Circle')),
                array('value'=>'social_tumblr_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Tumblr Circle')),
                array('value'=>'social_stumbleupon_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Stumbleupon Circle')),
                array('value'=>'social_wordpress_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Wordpress Circle')),
                array('value'=>'social_instagram_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Instagram Circle')),
                array('value'=>'social_dribbble_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Dribbble Circle')),
                array('value'=>'social_vimeo_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Vimeo Circle')),
                array('value'=>'social_linkedin_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Linkedin Circle')),
                array('value'=>'social_rss_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Rss Circle')),
                array('value'=>'social_deviantart_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Deviantart Circle')),
                array('value'=>'social_share_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Share Circle')),
                array('value'=>'social_myspace_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Myspace Circle')),
                array('value'=>'social_skype_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Skype Circle')),
                array('value'=>'social_youtube_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Youtube Circle')),
                array('value'=>'social_picassa_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Picassa Circle')),
                array('value'=>'social_googledrive_alt2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Googledrive Alt 2')),
                array('value'=>'social_flickr_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Flickr Circle')),
                array('value'=>'social_blogger_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Blogger Circle')),
                array('value'=>'social_spotify_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Spotify Circle')),
                array('value'=>'social_delicious_circle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Delicious Circle')),
                array('value'=>'social_facebook_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Facebook Square')),
                array('value'=>'social_twitter_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Twitter Square')),
                array('value'=>'social_pinterest_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Pinterest Square')),
                array('value'=>'social_googleplus_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Googleplus Square')),
                array('value'=>'social_tumblr_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Tumblr Square')),
                array('value'=>'social_stumbleupon_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Stumbleupon Square')),
                array('value'=>'social_wordpress_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Wordpress Square')),
                array('value'=>'social_instagram_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Instagram Square')),
                array('value'=>'social_dribbble_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Dribbble Square')),
                array('value'=>'social_vimeo_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Vimeo Square')),
                array('value'=>'social_linkedin_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Linkedin Square')),
                array('value'=>'social_rss_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Rss Square')),
                array('value'=>'social_deviantart_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Deviantart Square')),
                array('value'=>'social_share_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Share Square')),
                array('value'=>'social_myspace_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Myspace Square')),
                array('value'=>'social_skype_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Skype Square')),
                array('value'=>'social_youtube_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Youtube Square')),
                array('value'=>'social_picassa_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Picassa Square')),
                array('value'=>'social_googledrive_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Googledrive Square')),
                array('value'=>'social_flickr_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Flickr Square')),
                array('value'=>'social_blogger_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Blogger Square')),
                array('value'=>'social_spotify_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Spotify Square')),
                array('value'=>'social_delicious_square','label'=>Mage::helper('adminhtml')->__('ElegantIcons Social Delicious Square')),
                array('value'=>'icon_printer','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Printer')),
                array('value'=>'icon_calulator','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Calulator')),
                array('value'=>'icon_building','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Building')),
                array('value'=>'icon_floppy','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Floppy')),
                array('value'=>'icon_drive','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Drive')),
                array('value'=>'icon_search-2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Search 2 ')),
                array('value'=>'icon_id','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Id')),
                array('value'=>'icon_id-2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Id 2 ')),
                array('value'=>'icon_puzzle','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Puzzle')),
                array('value'=>'icon_like','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Like')),
                array('value'=>'icon_dislike','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Dislike')),
                array('value'=>'icon_mug','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mug')),
                array('value'=>'icon_currency','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Currency')),
                array('value'=>'icon_wallet','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Wallet')),
                array('value'=>'icon_pens','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pens')),
                array('value'=>'icon_easel','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Easel')),
                array('value'=>'icon_flowchart','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Flowchart')),
                array('value'=>'icon_datareport','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Datareport')),
                array('value'=>'icon_briefcase','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Briefcase')),
                array('value'=>'icon_shield','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Shield')),
                array('value'=>'icon_percent','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Percent')),
                array('value'=>'icon_globe','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Globe')),
                array('value'=>'icon_globe-2','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Globe 2 ')),
                array('value'=>'icon_target','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Target')),
                array('value'=>'icon_hourglass','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Hourglass')),
                array('value'=>'icon_balance','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Balance')),
                array('value'=>'icon_rook','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Rook')),
                array('value'=>'icon_printer-alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Printer Alt')),
                array('value'=>'icon_calculator_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Calculator Alt')),
                array('value'=>'icon_building_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Building Alt')),
                array('value'=>'icon_floppy_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Floppy Alt')),
                array('value'=>'icon_drive_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Drive Alt')),
                array('value'=>'icon_search_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Search Alt')),
                array('value'=>'icon_id_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Id Alt')),
                array('value'=>'icon_id-2_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Id 2  Alt')),
                array('value'=>'icon_puzzle_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Puzzle Alt')),
                array('value'=>'icon_like_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Like Alt')),
                array('value'=>'icon_dislike_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Dislike Alt')),
                array('value'=>'icon_mug_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Mug Alt')),
                array('value'=>'icon_currency_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Currency Alt')),
                array('value'=>'icon_wallet_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Wallet Alt')),
                array('value'=>'icon_pens_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Pens Alt')),
                array('value'=>'icon_easel_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Easel Alt')),
                array('value'=>'icon_flowchart_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Flowchart Alt')),
                array('value'=>'icon_datareport_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Datareport Alt')),
                array('value'=>'icon_briefcase_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Briefcase Alt')),
                array('value'=>'icon_shield_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Shield Alt')),
                array('value'=>'icon_percent_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Percent Alt')),
                array('value'=>'icon_globe_alt','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Globe Alt')),
                array('value'=>'icon_clipboard','label'=>Mage::helper('adminhtml')->__('ElegantIcons Icon Clipboard'))
            );
        }
		return $this->_options;
    }
}
